max_seq_len: 1000


#################### adin vc ######################
content_encoder:
  c_in: 512
  c_h: 128
  c_out: 128
  kernel_size: 5
  bank_size: 8
  bank_scale: 1
  c_bank: 128
  n_conv_blocks: 6
  subsample: [1, 2, 1, 2, 1, 2]
  act: 'relu'
  dropout_rate: 0  
  VQencoder:
        in_channels: 80
        channels: 512
        n_embeddings: 512
        z_dim: 128
        c_dim: 256

style_encoder:
  c_in: 512
  c_h: 128
  c_out: 128
  kernel_size: 5
  bank_size: 8
  bank_scale: 1
  c_bank: 128
  n_conv_blocks: 6
  n_dense_blocks: 6
  subsample: [1, 2, 1, 2, 1, 2]
  act: 'relu'
  dropout_rate: 0

decoder:
  c_in: 512
  c_cond: 128
  c_h: 128
  c_out: 512
  kernel_size: 5
  n_conv_blocks: 6
  upsample: [2, 1, 2, 1, 2, 1]
  act: 'relu'
  sn: False
  dropout_rate: 0
#################### adin vc ######################




#################### transformer tts ###############
DecoderPrenet:
  dprenet_layers: 2
  dropout_rate: 0.5
  n_layers: 2
  idim: 80
  n_units: 256
  dprenet_units: 256
  adim: 512


SpectrogramEncoder:
  c_in: 512
  dim_neck: 1024


SpectrogramDecoder:
  dim_neck: 1024
  dim_pre: 512


#################### transformer tts ###############


spks:
  multi_speaker: True
  use_spk_dvec: True  # for one-shot VC
  num_speakers: 109
  spk_embed_dim: 256

styles:
  multi_styles: True
  num_styles: 3
  style_embed_dim: 256

max_seq_len: 1000

vocoder:
  model: "MelGAN" # support 'HiFi-GAN', 'MelGAN'
  speaker: "universal" # support  'LJSpeech', 'universal'


# decoder_autovc:
#   frames_per_step: 1
#   dim_content: 64
#   dim_style: 32
#   dim_pre: 512
#   n_lstm_layers: 3
#   act: 'relu'
#   kernel_size: 5
#   stride: 1
#   padding: 2
#   dilation: 1