# dataset: "LibriTTS"
dataset: "VCTK"
data:
  train_fid_list: "/home/shaunxliu/data/vctk/fidlists/train_fidlist.new"
  validate_fid_list: "/home/shaunxliu/data/vctk/fidlists/dev_fidlist.new"
  test_fid_list: "/home/shaunxliu/data/vctk/fidlists/eval_fidlist.txt"

  vctk_wav_dir: "/home/v-jiewang/data/VCTK-corpus/VCTK-Corpus/wav16_downsample_trim_topdb30_flatten"
  raw_path: "./raw_data/VCTK"
  # vctk_spk_dvec_dir: "/home/shaunxliu/data/vctk/GE2E_spkEmbed_step_5805000_perSpk"
  vctk_spk_dvec_dir: "/home/v-jiewang/data/VCTK-corpus/VCTK-Corpus/wav16_downsample_trim_topdb30_d_vector_flatten_12000/"
  wav_file_ext: "wav"
  min_max_norm_mel: false
  # mel_min: -12.0
  # mel_max: 2.5  


path:
  # corpus_path: "/home/v-jiewang/data/LibriTTS/LibriTTS/train-clean-360"
  # lexicon_path: "lexicon/librispeech-lexicon.txt"
  # raw_path: "./raw_data/LibriTTS"
  preprocessed_path: "./preprocessed_data/LibriTTS"

preprocessing:
  val_size: 512
  text:
    text_cleaners: ["english_cleaners"]
    language: "en"
  audio:
    sampling_rate: 16000
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
  energy:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
