# dataset: "LibriTTS"
dataset: "VCTK"
data:
  ######################################### 16k ################################################
  ########### local GCR path #############
  # train_fid_list: "./preprocessed_data/VCTK_16k/train.txt"
  # validate_fid_list: "./preprocessed_data/VCTK_16k/val.txt"
  # test_fid_list: "./preprocessed_data/VCTK_16k/test.txt"
  # vctk_wav_dir: "/home/v-jiewang/data/VCTK-corpus/VCTK-Corpus/wav16_downsample_trim_topdb30"
  # vctk_mel_dir : "/home/v-jiewang/SpeechDecompose/preprocessed_data/VCTK_16k/mel"
  # raw_path: "./raw_data/VCTK"
  # preprocessed_path: "./preprocessed_data/VCTK_16k"
  # vctk_spk_dvec_dir: "/home/v-jiewang/data/VCTK-corpus/VCTK-Corpus/wav16_downsample_trim_topdb30_d_vector_flatten/GE2E_spkEmbed_step_5805000"
  ########### local GCR path #############
  ########### azure blob storage path #############
  # raw_path: "/datablob/v-jiewang/Data/features_VCTK/SpeechDecompose/raw_data/VCTK"
  # vctk_wav_dir: "/datablob/v-jiewang/Data/VCTK_raw_data/wav16_downsample_trim_topdb30/"  
  # train_fid_list: "/datablob/v-jiewang/Data/features_VCTK/SpeechDecompose/preprocessed_data/VCTK_16k/train.txt"
  # validate_fid_list: "/datablob/v-jiewang/Data/features_VCTK/SpeechDecompose/preprocessed_data/VCTK_16k/val.txt"
  # test_fid_list: "/datablob/v-jiewang/Data/features_VCTK/SpeechDecompose/preprocessed_data/VCTK_16k/test.txt"
  # vctk_mel_dir : "/datablob/v-jiewang/Data/features_VCTK/SpeechDecompose/preprocessed_data/VCTK_16k/mel"
  # preprocessed_path: "/datablob/v-jiewang/Data/features_VCTK/SpeechDecompose/preprocessed_data/VCTK_16k"
  # vctk_spk_dvec_dir: "/datablob/v-jiewang/Data/features_VCTK/SpeechDecompose/wav16_downsample_trim_topdb30_d_vector_flatten/GE2E_spkEmbed_step_5805000/"  
  ########### azure blob storage path #############
  ######################################### 16k ################################################

  ######################################### 22050 from 48k no trim ################################################
  ########### local GCR path #############
  # raw_path: "./raw_data/VCTK_22050"
  # train_fid_list: "./preprocessed_data/VCTK_22050/train.txt"
  # validate_fid_list: "./preprocessed_data/VCTK_22050/val.txt"
  # test_fid_list: "./preprocessed_data/VCTK_22050/test.txt"
  # vctk_wav_dir: "/home/v-jiewang/data/VCTK-corpus/VCTK-Corpus/wav48"
  # vctk_mel_dir : "/home/v-jiewang/SpeechDecompose/preprocessed_data/VCTK_22050/mel"
  # preprocessed_path: "./preprocessed_data/VCTK_22050"
  # vctk_spk_dvec_dir: "/home/v-jiewang/data/VCTK-corpus/VCTK-Corpus/wav16_downsample_trim_topdb30_d_vector_flatten/GE2E_spkEmbed_step_5805000"
  ########### local GCR path #############
  ########### azure blob storage path #############
  # raw_path: "/datablob/v-jiewang/Data/features_VCTK/SpeechDecompose/raw_data/VCTK_22050"
  # vctk_wav_dir: "/datablob/v-jiewang/Data/VCTK_raw_data/wav48/"  
  # train_fid_list: "/datablob/v-jiewang/Data/features_VCTK/SpeechDecompose/preprocessed_data/VCTK_22050/train.txt"
  # validate_fid_list: "/datablob/v-jiewang/Data/features_VCTK/SpeechDecompose/preprocessed_data/VCTK_22050/val.txt"
  # test_fid_list: "/datablob/v-jiewang/Data/features_VCTK/SpeechDecompose/preprocessed_data/VCTK_22050/test.txt"
  # vctk_mel_dir : "/datablob/v-jiewang/Data/features_VCTK/SpeechDecompose/preprocessed_data/VCTK_22050/mel"
  # preprocessed_path: "/datablob/v-jiewang/Data/features_VCTK/SpeechDecompose/preprocessed_data/VCTK_22050"
  # vctk_spk_dvec_dir: "/datablob/v-jiewang/Data/features_VCTK/SpeechDecompose/wav16_downsample_trim_topdb30_d_vector_flatten/GE2E_spkEmbed_step_5805000/"  
  ########### azure blob storage path #############
  ######################################### 22050 from 48k no trim ################################################

  ######################################### 22050 trim topdb 30 ################################################
  ########### local GCR path #############
  # raw_path: "./raw_data/VCTK_22050_trim30"
  # train_fid_list: "./preprocessed_data/VCTK_22050_trim30/train.txt"
  # validate_fid_list: "./preprocessed_data/VCTK_22050_trim30/val.txt"
  # test_fid_list: "./preprocessed_data/VCTK_22050_trim30/test.txt"
  # vctk_wav_dir: "/home/v-jiewang/data/VCTK-corpus/VCTK-Corpus/wav48"
  # vctk_mel_dir : "/home/v-jiewang/SpeechDecompose/preprocessed_data/VCTK_22050_trim30/mel"
  # preprocessed_path: "./preprocessed_data/VCTK_22050_trim30"
  # vctk_spk_dvec_dir: "/home/v-jiewang/data/VCTK-corpus/VCTK-Corpus/wav16_downsample_trim_topdb30_d_vector_flatten/GE2E_spkEmbed_step_5805000"
  ########### local GCR path #############

  ########### azure blob storage path #############
  raw_path: "/datablob/v-jiewang/Data/features_VCTK/SpeechDecompose/raw_data/VCTK_22050_trim30"
  vctk_wav_dir: "/datablob/v-jiewang/Data/VCTK_raw_data/wav48/"  
  train_fid_list: "/datablob/v-jiewang/Data/features_VCTK/SpeechDecompose/preprocessed_data/VCTK_22050_trim30/train.txt"
  validate_fid_list: "/datablob/v-jiewang/Data/features_VCTK/SpeechDecompose/preprocessed_data/VCTK_22050_trim30/val.txt"
  test_fid_list: "/datablob/v-jiewang/Data/features_VCTK/SpeechDecompose/preprocessed_data/VCTK_22050_trim30/test.txt"
  vctk_mel_dir : "/datablob/v-jiewang/Data/features_VCTK/SpeechDecompose/preprocessed_data/VCTK_22050_trim30/mel"
  preprocessed_path: "/datablob/v-jiewang/Data/features_VCTK/SpeechDecompose/preprocessed_data/VCTK_22050_trim30"
  vctk_spk_dvec_dir: "/datablob/v-jiewang/Data/features_VCTK/SpeechDecompose/wav16_downsample_trim_topdb30_d_vector_flatten/GE2E_spkEmbed_step_5805000/"  
  ########### azure blob storage path #############
  ######################################### 22050 trim topdb 30  ################################################

  wav_file_ext: "wav"
  mel_file_ext: "npy"
  min_max_norm_mel: True
  mel_min: -12.0
  mel_max: 2.5  


preprocessing:
  audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:   
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    # mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
    mel_fmax: null
  spk_emb:
    pretrained: "./speaker_encoder/ckpt/pretrained_bak_5805000.pt"
  # pitch:
  #   feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
  #   normalization: True
  energy:
    feature: "frame_level" # support 'phoneme_level' or 'frame_level'
    normalization: True

fig_path:
  direct_mel_from_acoustic_model: "./direct_mel_from_acoustic_model/"
  extract_from_wav_genrated_vocoder: "./extract_from_wav_genrated_vocoder/"
