path:
  ckpt_path: "./output_plot_mismatch_vocoder_for_thursday/ckpt/VCTK"
  log_path: "./output_plot_mismatch_vocoder_for_thursday/log/VCTK"
  result_path: "./output_plot_mismatch_vocoder_for_thursday/result/VCTK"
optimizer:
  batch_size: 16
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
lambda:
  lambda_rec: 10
  lambda_kl: 1
  lambda_vq: 10
  annealing_iters: 20000


step:
  total_step: 900000
  log_step: 1000
  synth_step: 1000
  val_step: 1000
  save_step: 100000
ddp:
  distributed_run: True
  seed: 1234
  num_workers: 16
  fp16_run: False
  cudnn_enabled: True
  cudnn_benchmark: True
  
  

